 version: '3'
 services:
        grafana:
                image: grafana/grafana 
                container_name: grafana
                restart: always 
                ports: 
                    - 3000:3000 
                depends_on:
                        - influxdb
        influxdb:
               image: influxdb
               container_name: influxdb 
               restart: always
               environment:
                     INFLUXDB_DB: telegraph 
                     INFLUXDB_ADMIN_ENABLED: "true"
                     INFLUXDB_ADMIN_USER: admin
                     INFLUXDB_ADMIN_PASSWORD: secretpassword
                     INFLUXDB_USER: telegraph
                     INFLUX_USER_PASSWORD: secretpassword
               ports:
                       - 8086:8086
    
